kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: httpd

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: abc3.com
    http:
      paths:
      - path: /
        backend:
          serviceName: httpd
          servicePort: http

