# monitor edilmeden bilgi toplanamaz!

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: traefik
    prometheus: kube-prometheus
    release: prometheus
  name: traefik
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: traefik
    path: /metrics

  namespaceSelector:
    matchNames:
    - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik