apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.13.0
  name: traefik-internal
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: traefik
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  type: ClusterIP
status: 
  loadBalancer: {}